import type { Metadata } from 'next'; // Added this import

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

// Add : {children: React.ReactNode} to define the type
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
